Typo in bash/2021/README.md

diff --git a/go/2015/days/MAKEDAY b/go/2015/days/MAKEDAY
--- a/go/2015/days/MAKEDAY
+++ b/go/2015/days/MAKEDAY
@@ -6,15 +6,15 @@ n="$1"
 [[ ${#n} == 1 ]] && n="0$n"
 
 name="day$n"
-year="${PWD##*/}"               # The current path must contain the year
+# The current path must contain the year
 [[ $PWD =~ go/([[:digit:]]{4})/ ]] && YYYY=${BASH_REMATCH[1]}
 
-[[ -e $name/$name.go ]] && { echo "ABORT: $name already exists"; exit 1;}
+[[ -e "$name/$name.go" ]] && { echo "ABORT: $name already exists"; exit 1;}
 
-mkdir -p $name
-cp ../TEMPLATES/TEST.go  $name/$name_test.go
+mkdir -p "$name"
+cp ../TEMPLATES/TEST.go  "$name/${name}_test.go"
 sed -r -e "s/YYYY/$YYYY/g" -e "s/dayNN/$name/g" \
-    <../TEMPLATES/INIT.go >$name/$name.go
-touch $name/input.txt
+    <../TEMPLATES/INIT.go >"$name/$name.go"
+touch "$name/input.txt"
 
-echo "Generated $name/$name.go $name/$name_test.go $name/input.txt in $name/"
+echo "Generated $name/$name.go $name/${name}_test.go $name/input.txt in $name/"
