Go 2016 day 16

diff --git a/go/2016/days/MAKEDAY b/go/2016/days/MAKEDAY
--- a/go/2016/days/MAKEDAY
+++ b/go/2016/days/MAKEDAY
@@ -1,15 +1,26 @@
 #!/bin/bash
 # Usage: MAKEDAY N
 # creates the set of files for day N
+
+err() { echo "***ERROR: $*"; exit 1;}
+
 n="$1"
-[[ $n =~ ^[[:digit:]]+$ ]] || { echo "Usage: MAKEDAY N"; exit 1;}
+[[ $n =~ ^[[:digit:]]+$ ]] || err "Usage: MAKEDAY N"
 [[ ${#n} == 1 ]] && n="0$n"
 
 name="d$n"
-# The current path must contain the year
-[[ $PWD =~ go/([[:digit:]]{4})/ ]] && YYYY=${BASH_REMATCH[1]}
+if [[ $PWD =~ go/([[:digit:]]{4})/ ]]; then
+    YYYY=${BASH_REMATCH[1]}
+else
+    err "The current path must contain the year: $PWD"
+fi
+if [[ $PWD =~ ^(.*/days)/d ]]; then
+    cd "${BASH_REMATCH[1]}" || exit
+elif ! [[ $PWD =~ /days ]]; then
+    err "MAKEDAY must be run from dir days/"   
+fi
 
-[[ -e "$name/$name.go" ]] && { echo "ABORT: $name already exists"; exit 1;}
+[[ -e "$name/$name.go" ]] && err "$name already exists"
 
 mkdir -p "$name"
 #cp ../../TEMPLATES/TEST.go  "$name/${name}_test.go"
@@ -18,5 +29,5 @@ sed -r -e "s/YYYY/$YYYY/g" -e "s/dNN/$name/g" \
     <../../TEMPLATES/INIT.go >"$name/$name.go"
 touch "$name/input.txt" "$name/example.txt" 
 
-echo "Generated $name/$name.go $name/${name}_test.go $name/input.txt $name/example.txt in $name/"
+echo "Generated $name/$name.go $name/input.txt $name/example.txt in $name/"
 
